import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  const cardContents = [
    {
      href: "https://nextjs.org/docs",
      title: "Documentation →",
      desc: "Find in-depth information about Next.js features and API.",
    },
    {
      href: "https://nextjs.org/learn",
      title: "Learn →",
      desc: "Learn about Next.js in an interactive course with quizzes!",
    },
    {
      href: "https://github.com/vercel/next.js/tree/canary/examples",
      title: "Examples →",
      desc: "Discover and deploy boilerplate example Next.js projects.",
    },
    {
      href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
      title: "Deploy →",
      desc: "Instantly deploy your Next.js site to a public URL with Vercel.",
    },
  ];
  const cards = cardContents.map((cardContent, index) => (
    <a
      key={`card-${index}`}
      href={cardContent.href}
      className="m-4 p-6 text-left text-inherit no-underline
            border-t-1 border-solid border-current rounded-lg transition border-current max-w-xs
            hover:underline force:underline active:underline
            hover:text-blue-600 force:text-blue-600 active:text-blue-600
            hover:border-blue-600 force:border-blue-600 active:border-blue-600"
    >
      <h2 className="m-t-4 text-base">{cardContent.title}</h2>
      <p className="m-0 text-sm">{cardContent.desc}</p>
    </a>
  ));
  return (
    <div className="py-0 px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 px-0 flex flex-1 flex-col justify-center items-center">
        <h1 className="m-0 text-7xl text-center">
          Welcome to{" "}
          <a
            className="text-blue-600 no-underline hover:underline force:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>
        <p className="mx-0 my-16 text-base text-center">
          Get started by editing{" "}
          <code className="rounded-md p-3 text-base font-mono">
            pages/index.tsx
          </code>
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-4xl">
          {cards}
        </div>
      </main>

      <footer className="flex flex-1 py-4 px-0 border-t-1 border-solid border-current justify-center items-center">
        <a
          className="flex justify-center items-center grow"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
